/**
 * The actions that StoriesList uses for Redux.
 *
 * @type {object}
 */
export default {
  STORY_LIST_REQUESTED: 'STORY_LIST_REQUESTED',
  STORY_LIST_SUCCEEDED: 'STORY_LIST_SUCCEEDED',
  TOGGLE_CHECKBOX_FILTER: 'TOGGLE_CHECKBOX_FILTER',
  TOGGLE_RADIOBUTTON_FILTER: 'TOGGLE_RADIOBUTTON_FILTER',
  CLEAR_RADIOBUTTON_FILTER: 'CLEAR_RADIOBUTTON_FILTER',
}
