/**
 * Story specific constants used for Redux state management.
 *
 * @type {object}
 */
export default {
  // Actions.
  STORY_BODY_CHANGED: 'STORY_BODY_CHANGED',
  STORY_HEADLINE_CHANGED: 'STORY_HEADLINE_CHANGED',
  STORY_BYLINE_CHANGED: 'STORY_BYLINE_CHANGED',
  STORY_PRIMARY_AUDIO_CHANGED: 'STORY_PRIMARY_AUDIO_CHANGED',
  STORY_PRIMARY_AUDIO_REMOVED: 'STORY_PRIMARY_AUDIO_REMOVED',
  STORY_PRIMARY_IMAGE_CHANGED: 'STORY_PRIMARY_IMAGE_CHANGED',
  STORY_PRIMARY_IMAGE_REMOVED: 'STORY_PRIMARY_IMAGE_REMOVED',

  STORY_PRIMARY_IMAGE_METADATA_SAVE_REQUESTED: 'STORY_PRIMARY_IMAGE_METADATA_SAVE_REQUESTED',
  STORY_PRIMARY_IMAGE_METADATA_CAPTION_CHANGE: 'STORY_PRIMARY_IMAGE_METADATA_CAPTION_CHANGE',
  STORY_PRIMARY_IMAGE_METADATA_CREDIT_CHANGE: 'STORY_PRIMARY_IMAGE_METADATA_CREDIT_CHANGE',
  STORY_PRIMARY_IMAGE_METADATA_AGENCY_CHANGE: 'STORY_PRIMARY_IMAGE_METADATA_AGENCY_CHANGE',

  STORY_PRIMARY_IMAGE_METADATA_CHANGED: 'STORY_PRIMARY_IMAGE_METADATA_CHANGED',

  STORY_SAVE_REQUESTED: 'STORY_SAVE_REQUESTED',
  STORY_LOAD_REQUESTED: 'STORY_LOAD_REQUESTED',
  STORY_LOAD_SUCCEEDED: 'STORY_LOAD_SUCCEEDED',
  STORY_RESET: 'STORY_RESET',

  PRIMARY_AUDIO_RESET: 'PRIMARY_AUDIO_RESET',
  PRIMARY_AUDIO_DURATION_RESET: 'PRIMARY_AUDIO_DURATION_RESET',
  PRIMARY_AUDIO_SCRUBBER_PROGRESS_CHANGED: 'PRIMARY_AUDIO_SCRUBBER_PROGRESS_CHANGED',
  PRIMARY_AUDIO_CURRENT_TIME_CHANGED: 'PRIMARY_AUDIO_CURRENT_TIME_CHANGED',
  PRIMARY_AUDIO_SCRUBBER_WIDTH_CHANGED: 'PRIMARY_AUDIO_SCRUBBER_WIDTH_CHANGED',
  PRIMARY_AUDIO_TOGGLE_PLAY: 'PRIMARY_AUDIO_TOGGLE_PLAY',
  SET_PRIMARY_AUDIO_ELEMENT: 'SET_PRIMARY_AUDIO_ELEMENT',
  PRIMARY_AUDIO_MOUSE_IS_DOWN: 'PRIMARY_AUDIO_MOUSE_IS_DOWN',
  PRIMARY_AUDIO_TOGGLE_TIMESTAMP: 'PRIMARY_AUDIO_TOGGLE_TIMESTAMP',
  PRIMARY_AUDIO_SET_X_POSITION: 'PRIMARY_AUDIO_SET_X_POSITION',
  STORY_VALIDATION_FAILED: 'STORY_VALIDATION_FAILED',
  STORY_VALIDATION_SUCCEEDED: 'STORY_VALIDATION_SUCCEEDED',

  // Array of required story fields (field names). Used during story validation before save/publish.
  REQUIRED_FIELDS: ['headline', 'body'],

  // Types of errors that can be reported by the application. Referred to when reporting errors.
  ERROR_TYPES: {
    MISSING: 'MISSING_CONTENT',
  },

  // General error message copy for rendering story errors.
  ERROR_MESSAGES: {
    REQUIRED_FIELDS:
      'To save and/or publish, you need at least one topic, a headline, and some body copy.',
    INVALID_FIELDS: 'Please correct the highlighted fields and try again.',
  },
}
